### ISSUE TITLE
MCIR docker image

### ISSUE THREAD

**Issue by andresriancho** [SpiderLabs/MCIR#3]
Hi @unicornFurnace , I would like to create a docker image for MCIR, something really [similar to what I did for sqlmap's testenv](https://github.com/sqlmapproject/testenv/pull/8)

This is part of my efforts to [improve w3af's test suite](https://github.com/andresriancho/w3af/issues/8694) by adding MCIR as a test application.

My questions are:
 * Would you be interested in a pull request [like this](https://github.com/sqlmapproject/testenv/pull/8) ?
 * Any recommendations or things I need to take into account while building the docker image?
 * Are [these](https://github.com/SpiderLabs/MCIR/blob/master/autoinstall.sh) all the steps required to setup MCIR?
 * Which distribution do you run autoinstall.sh in? (debian? ubuntu? which version?)

**Comment by unicornsasfuel** [comment]
Hi Andres,

To answer your questions:

* Yes, I'd be interested in a pull request to help make MCIR more docker-friendly. I haven't much experience with it, but I know what it can do and I've been thinking about how I can make MCIR easier to deploy for educators, tool devs, students, etc.
* MCIR is pretty self-contained, but if you have issues I'll be happy to help.
* `autoinstall.sh` should be all you need to get going, unless you want to use a database system besides MySQL for SQLol, in which case there's a configuration file you need to update at `/sqlol/includes/database.config.php`.
* The autoinstall script should allow you to get MCIR running in any distro with apt-get, but it was last tested in Ubuntu 14.04, IIRC.

Regards,
--
Daniel Crowley

**Comment by unicornsasfuel** [comment]
Closed, thank you Andres!
